Repository XceeDesigns/Website, pull requests merged in 2024-05, with the labels that each got.

#70 Added CONTRIBUTINGS.md
  CONTRIBUTINGS.md
Labels: documentation, good first issue, level2

#30 added comments
  contact-dashboard.html
  contact-dashboard.js
  contact.js
Labels: good first issue, gssoc, level2

#88 Enhancement: Added Animation to images
  css/style.css
Labels: gssoc, level2

#97 Added Greeting bot
  .github/workflows/greetings.yml
Labels: good first issue, gssoc, level2

#92 Reusable NavBar Component adding in react app without js applied
  frontend/css/AjaxLoader.gif
  frontend/css/animate.min.css
  frontend/css/bootstrap-datetimepicker.min.css
  frontend/css/bootstrap-theme.css.map
  frontend/css/bootstrap-theme.min.css
  frontend/css/bootstrap.css.map
  frontend/css/bootstrap.min.css
  frontend/css/boxed.css
  frontend/css/flexslider-for-posts.css
  frontend/css/flexslider.css
  frontend/css/fonts/flexslider-icon.eot
  frontend/css/fonts/flexslider-icon.svg
  frontend/css/fonts/flexslider-icon.ttf
  frontend/css/fonts/flexslider-icon.woff
  frontend/css/grabbing.png
  frontend/css/icons-fonts.css
  frontend/css/ie-warning.css
  frontend/css/ie8-fix.css
  frontend/css/owl-carousel/AjaxLoader.gif
  frontend/css/owl-carousel/grabbing.png
  frontend/css/owl-carousel/owl.carousel.css
  frontend/css/owl-carousel/owl.theme.css
  frontend/css/owl-carousel/owl.transitions.css
  frontend/css/style.css
  frontend/css/text-rotator.css
  frontend/css/twentytwenty-no-compass.css
  frontend/css/twentytwenty.css
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.jsx
  frontend/src/assets/Images/logo-new.png
  frontend/src/assets/react.svg
  frontend/src/components/Navbar.jsx
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: gssoc, level3

#109 Added comments
  index.html
  robots.txt
Labels: enhancement, good first issue, level3

#125 Recreated Complete Navbar with React+Tailwind
  .vscode/settings.json
  frontend/css/AjaxLoader.gif
  frontend/css/animate.min.css
  frontend/css/bootstrap-datetimepicker.min.css
  frontend/css/bootstrap-theme.css.map
  frontend/css/bootstrap-theme.min.css
  frontend/css/bootstrap.css.map
  frontend/css/bootstrap.min.css
  frontend/css/boxed.css
  frontend/css/flexslider-for-posts.css
  frontend/css/flexslider.css
  frontend/css/fonts/flexslider-icon.eot
  frontend/css/fonts/flexslider-icon.svg
  frontend/css/fonts/flexslider-icon.ttf
  frontend/css/fonts/flexslider-icon.woff
  frontend/css/grabbing.png
  frontend/css/icons-fonts.css
  frontend/css/ie-warning.css
  frontend/css/ie8-fix.css
  frontend/css/owl-carousel/AjaxLoader.gif
  frontend/css/owl-carousel/grabbing.png
  frontend/css/owl-carousel/owl.carousel.css
  frontend/css/owl-carousel/owl.theme.css
  frontend/css/owl-carousel/owl.transitions.css
  frontend/css/style.css
  frontend/css/text-rotator.css
  frontend/css/twentytwenty-no-compass.css
  frontend/css/twentytwenty.css
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/logo-new.png
  frontend/src/components/App.css
  frontend/src/components/Contact.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Nav.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Service.jsx
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: enhancement, gssoc, level2

#137 Loader added when submitting contact form
  contact.html
  css/style.css
Labels: gssoc, level2

#143 Added react Icon and react router dom dependencies to deploy the frontend branch
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
Labels: good first issue, gssoc, level1

#153 Loader responsive added for mobile view
  css/style.css
Labels: good first issue, gssoc, level2

#154 solves issue # 144 X-done
  font-6/css/all.css
  font-6/css/all.min.css
  font-6/css/brands.css
  font-6/css/brands.min.css
  font-6/css/fontawesome.css
  font-6/css/fontawesome.min.css
  font-6/css/regular.css
  font-6/css/regular.min.css
  font-6/css/solid.css
  font-6/css/solid.min.css
  font-6/css/svg-with-js.css
  font-6/css/svg-with-js.min.css
  font-6/css/v4-font-face.css
  font-6/css/v4-font-face.min.css
  font-6/css/v4-shims.css
  font-6/css/v4-shims.min.css
  font-6/css/v5-font-face.css
  font-6/css/v5-font-face.min.css
  font-6/webfonts/fa-brands-400.ttf
  font-6/webfonts/fa-brands-400.woff2
  font-6/webfonts/fa-regular-400.ttf
  font-6/webfonts/fa-regular-400.woff2
  font-6/webfonts/fa-solid-900.ttf
  font-6/webfonts/fa-solid-900.woff2
  font-6/webfonts/fa-v4compatibility.ttf
  font-6/webfonts/fa-v4compatibility.woff2
  index.html
Labels: gssoc, level1
