Repository XceeDesigns/Website, pull requests merged in 2024-06, with the labels that each got.

#171 added deployed link in REadme
  README.md
  frontend/public/vite.svg
Labels: good first issue, gssoc, level1

#175 Map Updated for mobile screen
  contact.html
  css/style.css
Labels: bug, gssoc, level1

#177 Recreate Contact Page in React : Issue #47
  frontend/index.html
  frontend/src/App.jsx
  frontend/src/components/App.css
  frontend/src/components/Contact.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/Logo.jsx
  frontend/src/components/Nav.jsx
Labels: gssoc, level3

#178 Changed photos on Services page
  css/style.css
  images/performance-01.png
  images/responsive.png
  index.html
  services.html
Labels: good first issue, gssoc, level2

#182 Fixed added autofocused to the input field #156
  index.html
Labels: bug, gssoc, level1

#184 Fixed responsiveness and added correct deployment link
  README.md
  frontend/src/App.jsx
  frontend/src/components/App.css
  frontend/src/components/Contact.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/Nav.jsx
  frontend/tailwind.config.js
Labels: gssoc, level1

#188 fix : fixed copyright_bug
  index.html
Labels: good first issue, gssoc, level1

#195 Final enhancements of issue #47
  frontend/src/App.jsx
  frontend/src/components/App.css
  frontend/src/components/Contact.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/Home.jsx
  frontend/src/components/Nav.jsx
  frontend/src/components/Service.jsx
  frontend/tailwind.config.js
Labels: gssoc, level1

#197 Fixed the Instagram logo in Footer Across pages!
  contact.html
  services.html
Labels: good first issue, gssoc, level1

#216 Submit when clicked on enter
  contact.html
Labels: gssoc, level2

#217 Improved SEO of the website
  index.html
Labels: gssoc, level2

#203 UI enhancement of back to top button
  css/style.css
Labels: gssoc, level2

#221 Message text area fixed
  contact.html
Labels: good first issue, gssoc, level1
